config/routes.rb
Rails.application.routes.draw do

  resources :votes
  devise_for :users
  root to: 'movies#index'

  resources :movies

  resources :users do
    resources :movies
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :votes
  belongs_to :user

  scope :ordered_by_likes,  -> { joins("LEFT JOIN votes ON votes.movie_id = movies.id").order("votes.like desc, movies.votes_count desc").uniq }
  scope :ordered_by_hates,  -> { joins("LEFT JOIN votes ON votes.movie_id = movies.id").order("votes.hate desc, movies.votes_count desc").uniq }
  scope :ordered_by_date,   -> { order(created_at: :asc) }

  # Returns count of likes, hates or all votes depending on `type` parameter.
  # By default returns `active` count.
  def votes_count(type = 'active')
    votes.send(type).count
  end

  def has_votes?(type = 'active')
    !votes_count(type).zero?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :votes
  has_many :movies

  validates :first_name, presence: true
  validates :last_name, presence: true

  def nickname
    @nickname ||= [first_name, last_name].join(" ")
  end

  def likes_movie?(movie)
    votes.likes.map(&:movie).include?(movie)
  end

  def hates_movie?(movie)
    votes.hates.map(&:movie).include?(movie)
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :movie

  scope :likes, -> { where(like: true) }
  scope :hates, -> { where(hate: true) }
  scope :active, -> { where(hate: true).or(Vote.where(like: true)) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :update, :destroy]
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    @movies = params[:user_id].present? ? Movie.where(user_id: params[:user_id]) : Movie.all
    @movies = @movies.send("ordered_by_#{params[:sort]}") unless params[:sort].blank?
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:user_id, :title, :description, :published_at)
    end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :set_vote, only: [:show, :edit, :update, :destroy]

  # GET /votes
  # GET /votes.json
  def index
    @votes = Vote.all
  end

  # GET /votes/1
  # GET /votes/1.json
  def show
  end

  # GET /votes/new
  def new
    @vote = Vote.new
  end

  # GET /votes/1/edit
  def edit
  end

  # POST /votes
  # POST /votes.json
  def create
    @vote = Vote.find_or_initialize_by(movie_id: vote_params[:movie_id], user_id: current_user.id)

    @vote.like = false
    @vote.hate = false

    @vote.update_attributes(vote_params)

    respond_to do |format|
      if @vote.save
        format.html { redirect_to movies_path, notice: 'Vote was successfully created.' }
        format.json { render :show, status: :created, location: @vote }
      else
        format.html { render :new }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /votes/1
  # PATCH/PUT /votes/1.json
  def update
    respond_to do |format|
      if @vote.update(vote_params)
        format.html { redirect_to @vote, notice: 'Vote was successfully updated.' }
        format.json { render :show, status: :ok, location: @vote }
      else
        format.html { render :edit }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /votes/1
  # DELETE /votes/1.json
  def destroy
    @vote.destroy
    respond_to do |format|
      format.html { redirect_to votes_url, notice: 'Vote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vote
      @vote = Vote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vote_params
      params.require(:vote).permit(:movie_id, :like, :hate)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper

  def get_user_nickname(movie)
    return '' unless movie.class == Movie
    movie.user == current_user ? 'You' : movie.user.nickname
  end
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/application/_header.html.erb
<div class="header">
  <div class="col">
    <h1 class="logo"><%= link_to "MovieRama", root_path %></h1>
  </div>
  <div class="col">
    <% if user_signed_in?%>
      Welcome back <%= link_to current_user.nickname, destroy_user_session_path, method: :delete %>
    <% else %>
      <span><%= link_to "Log_in", new_user_session_path %></span> or <span class="signup"><%= button_to "Sign up", new_user_registration_path, method: "get" %></span>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieRama</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
    <%= render "header" %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie, local: true) do |form| %>
  <%= form.hidden_field :user_id, value: current_user.id %>

  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :movie_title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :movie_description %>
  </div>

  <div class="field">
    <%= form.label :published_at %>
    <%= form.datetime_select :published_at, id: :movie_published_at %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/movies/_unvotes.html.erb
<% if current_user.likes_movie?(movie) %>
  <div class="col">
    You like this movie
    |
    <%= link_to 'Unlike', votes_path( vote: { movie_id: movie, like: false }), method: 'post' %>
  </div>
<% elsif current_user.hates_movie?(movie) %>
  <div class="col">
    You hate this movie
    |
    <%= link_to 'Unhate', votes_path( vote: { movie_id: movie, hate: false }), method: 'post' %>
  </div>
<% end %>

app/views/movies/_votes.html.erb
<% if user_signed_in? && movie.user != current_user %>
  <% if movie.has_votes? %>
    <div class="col">
      <% if current_user.likes_movie?(movie) %>
        <%= t('likes', count: movie.votes_count("likes")) %>
      <% else %>
        <%= link_to "#{t('likes', count: movie.votes_count("likes"))}", votes_path( vote: { movie_id: movie, like: true }), method: 'post' %>
      <% end %>
      |
      <% if current_user.hates_movie?(movie) %>
        <%= t('hates', count: movie.votes_count("hates")) %>
      <% else %>
        <%= link_to "#{t('hates', count: movie.votes_count("hates"))}", votes_path( vote: { movie_id: movie, hate: true }), method: 'post' %>
      <% end %>
    </div>
  <% else %>
    <div>
      <span>Be the first to vote for this movie: <%= link_to 'Like', votes_path( vote: { movie_id: movie, like: true }), method: 'post'%></span>
      |
      <span><%=link_to 'Hate', votes_path( vote: { movie_id: movie, hate: true }), method: 'post'%></span>
    </div>
  <% end %>
<% else %>
  <%= t('likes', count: movie.votes_count("likes")) %> | <%= t('hates', count: movie.votes_count("hates")) %>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>

<div class="toolbox">
Sort by:
<%= link_to 'Likes', movies_path(sort: 'likes') %>
|
<%= link_to 'Hates', movies_path(sort: 'hates') %>
|
<%= link_to 'Date', movies_path(sort: 'date') %>
</div>

<div class="main ilb">
  <% @movies.each do |movie| %>
    <div class="movie">
      <h2><%= movie.title%></h2>
      <p> Posted by <%= link_to get_user_nickname(movie), user_movies_path(movie.user) %> <%= time_ago_in_words(movie.published_at) %></p>
      <p><%= movie.description %></p>
      <%= render partial: "votes", locals: { movie: movie } %>
      <%= render partial: "unvotes", locals: { movie: movie } if user_signed_in? %>
    </div>
  <% end %>
</div>

<div class="aside ilb">
  <%= button_to 'New Movie', new_movie_path, method: "get", class: "button green" if user_signed_in? %>
</div>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @movie.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @movie.description %>
</p>

<p>
  <strong>Published at:</strong>
  <%= @movie.published_at %>
</p>

<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>

app/views/votes/_form.html.erb
<%= form_with(model: vote, local: true) do |form| %>
  <% if vote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vote.errors.count, "error") %> prohibited this vote from being saved:</h2>

      <ul>
      <% vote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :like %>
    <%= form.check_box :like, id: :vote_like %>
  </div>

  <div class="field">
    <%= form.label :hate %>
    <%= form.check_box :hate, id: :vote_hate %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/votes/edit.html.erb
<h1>Editing Vote</h1>

<%= render 'form', vote: @vote %>

<%= link_to 'Show', @vote %> |
<%= link_to 'Back', votes_path %>

app/views/votes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Votes</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Like</th>
      <th>Hate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @votes.each do |vote| %>
      <tr>
        <td><%= vote.type %></td>
        <td><%= vote.like %></td>
        <td><%= vote.hate %></td>
        <td><%= link_to 'Show', vote %></td>
        <td><%= link_to 'Edit', edit_vote_path(vote) %></td>
        <td><%= link_to 'Destroy', vote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vote', new_vote_path %>

app/views/votes/new.html.erb
<h1>New Vote</h1>

<%= render 'form', vote: @vote %>

<%= link_to 'Back', votes_path %>

app/views/votes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @vote.type %>
</p>

<p>
  <strong>Like:</strong>
  <%= @vote.like %>
</p>

<p>
  <strong>Hate:</strong>
  <%= @vote.hate %>
</p>

<%= link_to 'Edit', edit_vote_path(@vote) %> |
<%= link_to 'Back', votes_path %>